name: Build & release zip

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          mkdir -p dist
          zip -r dist/imou_control.zip custom_components/imou_control -x "*/__pycache__/*"
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/imou_control.zip
