set_position:
  name: Definir posição (PTZ absoluto)
  description: Move a câmera para a posição absoluta por h/v/z usando a API da Imou.
  fields:
    device_id:
      description: Device ID da câmera na Imou
      example: 5250FACPBV99ADE
    h:
      description: Posição horizontal (-1..1, conforme sua API)
      example: -0.60
    v:
      description: Posição vertical (-1..1, conforme sua API)
      example: 0.15
    z:
      description: Zoom (opcional; padrão 0)
      example: 0

register_device:
  name: Registrar dispositivo
  description: Adiciona manualmente um dispositivo à integração.
  fields:
    device_id:
      description: Device ID da câmera na Imou
      example: 5250FACPBV99ADE
    name:
      description: Nome amigável (opcional)
      example: Sala
    model:
      description: Modelo da câmera (opcional)
      example: IPC-A22EP
